### ISSUE TITLE
Constants in R2RML

### ISSUE THREAD

**Issue by xeniacs** [KGConf/BookClub-Designing-BuildingEnterpriseKG#10]
Could you please explain how a "constant" is used? I cannot get my head around it. Could we have an example from a dataset to a graph?

**Comment by rdfguy** [comment]
Just to clarify, are you referring to things like those discussed in sections 3.3.8, 3.3.9, and 3.3.10?

**Comment by msesboue** [comment]
Answered at the beginning of session 5
