### ISSUE TITLE
subjectMap in R2RML

### ISSUE THREAD

**Issue by xeniacs** [KGConf/BookClub-Designing-BuildingEnterpriseKG#11]
In the examples provided (2.13 - 2.15), the first one includes _rr:class :Customer_ to create a class out of the template. The other two examples do not include an _rr:class_ predicate (indeed, the text says this is optional), i.e., the subjectMap does not create a triple. Have I understood correctly? If so, what's the use of non-class subjects?

**Comment by msesboue** [comment]
discussed during session 3 after 16 minutes
