### ISSUE TITLE
Are there best practices or good reference implementations of modeling entity resolution with a KG?

### ISSUE THREAD

**Issue by eldredgeb** [KGConf/BookClub-Designing-BuildingEnterpriseKG#13]
I understand why you don't want to get into entity resolution itself as a topic in the book, but I'm wondering if there are known good ways to represent that two entities with different identifiers in different data sources are -- or likely are -- the same real-world entity. For instance, if I have a process by which I can identify with 95% confidence in that Visitor ABC is the same person as Customer 123, what are the ways I could model that?

**Comment by msesboue** [comment]
Discussed during session 3 after around 32 minutes
