### ISSUE TITLE
Direct mappings, Custom mappings, Direct custom mappings, and Complex custom mappings

### ISSUE THREAD

**Issue by xeniacs** [KGConf/BookClub-Designing-BuildingEnterpriseKG#15]
Chapter 2 speaks of Direct Mappings vs Custom Mappings.
Chapter 3 speaks of Direct Custom Mappings vs Complex Custom Mappings.
The terms have somewhat confused me. Let's take the phrase on p.45, "_The direct custom mappings are direct mappings with the ability to custom define the target, instead of creating the knowledge graph schema based on the source relational schema._" 
So, Direct Custom Mappings are Direct Mappings with a twist, right?
But then, if this were so, Complex Custom Mappings would be simply called Custom Mappings to match the term from Chapter 2, right?
So I'm getting something wrong...

**Comment by rdfguy** [comment]
Let's discuss this during the next session.
