### ISSUE TITLE
Modeling Time

### ISSUE THREAD

**Issue by eldredgeb** [KGConf/BookClub-Designing-BuildingEnterpriseKG#17]
In Example 3.4, the start timestamp of an event is modeled as a Relationship Attribute of the "placedBy" edge connecting the Concept "Order" to the Concept "Customer."  Later, different dates are modeled as Concept Attributes of the Concept "Customer." It seems like the approach to handling time, given its central role in many / most business analyses, is a key decision in modeling. It also seems to me that modeling at least Date if not Time (or subsets of time) as well as a Concept would offer a tremendous opportunity for conformance of format and thus queriability.  Are there best practices around modeling time?

**Comment by juansequeda** [comment]
It depends :) 

The issue is that time isn't first class citizen of the data model. Therefore it ends up being a modeling question.

Important read: https://martinfowler.com/articles/bitemporal-history.html
Also take a look at Time Ontology: https://www.w3.org/TR/owl-time/

**Comment by rdfguy** [comment]
One of my favorites: https://www.sciencedirect.com/science/article/abs/pii/0004370287900610

**Comment by msesboue** [comment]
Answered during session 4
