### ISSUE TITLE
Best formats for source data?

### ISSUE THREAD

**Issue by eldredgeb** [KGConf/BookClub-Designing-BuildingEnterpriseKG#20]
The book defines "Data Producers" as the producers of data products, which are the outputs of processes that make complex source data more consumable. But the original "producers" of the data are the application developers. If you have the opportunity to influence the format / structure of the source data, are there guidelines to provide to the application development teams that will make the data easier to integrate into an EKG?  JSON, I suppose, with a hierarchy that aligns with the intended Concepts in the EKG?

**Comment by msesboue** [comment]
discussed during session 5 after 25 minutes
