### ISSUE TITLE
how to capture reasoning in phase-1 knowledge report of iterative KG-building process?

### ISSUE THREAD

**Issue by dwinston** [KGConf/BookClub-Designing-BuildingEnterpriseKG#21]
Where might symbolic and statistical reasoning fit in to the "knowledge report" framework of Chapter 4, e.g. in Tables 4.2 through 4.4?

It seems that some decisions re: reasoning would directly impact trust in answers to business questions. For example, questions about "family members" (is a step-child's spouse included?) or about "outliers" (> 3 sigma for a fit normal distribution?) may rely on consistent symbolic and non-symbolic (statistical) characterizations, respectively, for which a C-suite report-reader would not want different data consumers, e.g. analysts, to produce different values based on the same data product, i.e. based on the same KG projection.

**Comment by msesboue** [comment]
Discussed at the beginning of sesssion 6
