### ISSUE TITLE
Methodology Phase 1

### ISSUE THREAD

**Issue by xeniacs** [KGConf/BookClub-Designing-BuildingEnterpriseKG#22]
These are more questions on best practices, i.e., best ways to document or share info that the knowledge scientist gathers and which I find rather difficult and complex to document and communicate.

Knowledge report:
Other than the CAR tables and the data product as a table, what else does the knowledge report need to include? For example, is this the place to document (in text) things like terminology discrepancies and relevant discussions? Or is it better to keep the knowledge report clean and short and keep the info that led to the report in a separate document?

Knowledge capture:
Could we view a What-Why-Who-How-Where-When table of a more complex case? For example, one with a question that implies several nested questions within. Or with several roles involved in the Who. Or with a Where that needs to enter into deeper details, for example: the producer has the information in an RDBMS, but has also the capability to triplify on-the-fly (with his own schema, not with mappings).

**Comment by msesboue** [comment]
Discussed at the beginning of session 7
