### ISSUE TITLE
resolution of figure 1.6?

### ISSUE THREAD

**Issue by dwinston** [KGConf/BookClub-Designing-BuildingEnterpriseKG#23]
![2022-03-23 09 29 38](https://user-images.githubusercontent.com/1497854/159711031-90856b5c-97f3-4c6c-a6db-a032fe06c121.jpg)

**Comment by dwinston** [comment]
See  https://github.com/KGConf/BookClub-Designing-BuildingEnterpriseKG/issues/7#issuecomment-1032974671

**Comment by dwinston** [comment]
e.g. where is the "data product manager"? the "knowledge scientist", "knowledge engineer", "ontologist", etc.? How is the "pay-as-you-go" iterative process ("knowledge capture", "knowledge implementation", "knowledge access") visualized in the visual language of the diagrams? This would strengthen the book's intent tremendously for me.

**Comment by msesboue** [comment]
discussed during session 7 after 23 minutes
