### ISSUE TITLE
how to navigate "build versus buy"?

### ISSUE THREAD

**Issue by dwinston** [KGConf/BookClub-Designing-BuildingEnterpriseKG#24]
As one of the headings in the last chapter says, "You Need a Data Team". At the same time, it's nice to delegate dev and support to external expert teams.

https://twitter.com/muckledown/status/1491960764650999809 :
> Those who choose the build path far too often only consider the “build” part. Not the training, management, & operations for the ongoing dev team OR the onboarding, management, training, updates, new features, and support for consumers of the product. Hubris is a helluva drug.

https://twitter.com/valeness84/status/1492172615993102344 :
> Those who consider the "buy" path will also often fail to consider this. I've seen people buy no-code tools that consist of a complex node editor and then fail to hire anyone who understands how to use it. You still need a team to run purchased solutions.

Are there general principles you've learned for which parts of the KG design/build/maintenance activities are most important/wise to BUILD vs BUY. And conversely?

**Comment by msesboue** [comment]
Discussed during session 7 after 45 minutes
