### ISSUE TITLE
Do you have some examples to further demonstrate the differences between, "relationships between data", "relationship within data" and "hard-wired in software"?

### ISSUE THREAD

**Issue by msesboue** [KGConf/BookClub-Designing-BuildingEnterpriseKG#3]
Chap 1, page 14, section 1.3.2

**Comment by rdfguy** [comment]
It is really "relationships between data *and definitions of data*. This one is simple, "definitions" here really means "classes", so identifying a node as an instance of a class. "Relationships within data" can be anything where one item of data being linked to (related to) another gives it some meaning (e.g., "part of" relationship may influence how you interpret a particular node/object). "Hard-wired in software" is what we have done traditionally: you have data, you write some code to manipulate that data (i.e., "interpret" that data).
