### ISSUE TITLE
Could you specify "_if it is not the last column in the primary key, the “;” character._"?

### ISSUE THREAD

**Issue by msesboue** [KGConf/BookClub-Designing-BuildingEnterpriseKG#4]
Chap 2, page 34, section 2.3.1, paragraph Direct Mappings to RDF Graphs, I fail to understand what "_the last column in the primary key_" refers to. Could you give an example?

**Comment by dwinston** [comment]
For a table Person with columns (first_name, last_name, birth_date, description),
it's possible that the primary key may be a compound key, e.g. (first_name, last_name, birth_date) to uniquely identify a row (if there is no "ID" column). So in this case, the "last column" would be birth_date.

**Comment by msesboue** [comment]
Thank you 
It makes sense now :)
