### ISSUE TITLE
How does one avoid Trojan-horsing hard-wired software for mappings?

### ISSUE THREAD

**Issue by dwinston** [KGConf/BookClub-Designing-BuildingEnterpriseKG#6]
You state that semantics are embodied pragmatically in three ways:
1. relationships between data (e.g. USD <-> currency),
2. relationships within data (e.g. (10 <-> USD), and
3. hard-wired in software (e.g. calculation of net sales).

It seems like a knowledge graph approach could simply Trojan-horse hard-wired software rather than really embed logic in the data and the definitions of data. In other words, figure 1.5 turns into figure 1.6 by simply cutting the static connectors between the data sources at left, the Data Prep Tools in the middle, and the data consumers at right, leaving a soup of Data Prep Tools living in the Data-Meaning gap and calling the system a knowledge graph. The semantics are still mostly hard-wired in software. More than one data consumer can e.g. call calculationOfNetSales as part of a graph query, but there is still a soup of software to maintain, upgrade, etc.

*How does one avoid this Trojan-horsing when implementing mappings?* It seems like a given Data Prep Tool / ontology concept "node" could just be a hairball of a query (figure 1.2) under the hood.

**Comment by dwinston** [comment]
@msesboue I can't add labels to my issue. please advise.

**Comment by msesboue** [comment]
@dwinston can you try now please? I changed your access writes

**Comment by dwinston** [comment]
@msesboue I am still unable to apply labels to the issue. I confirmed that I can do so on another repo, so I am logged in.

**Comment by dwinston** [comment]
Ah, I needed to accept an invitation first. Done now. Thank you.

**Comment by msesboue** [comment]
Suggestion is to discuss this topic during the last session --> what would be "figure 1.7"

**Comment by msesboue** [comment]
discussed during session 3 after about 45 minutes
