### ISSUE TITLE
Data warehouse/lake approach, but with a KG

### ISSUE THREAD

**Issue by xeniacs** [KGConf/BookClub-Designing-BuildingEnterpriseKG#7]
If we change the role names of Figure 1.3. (e.g., we put a KG developer or Ontologist instead of a Data Architect) and we replace the Enterprise Data Warehouse with say a Triple Store, then we pretty much get what is currently happening in several organisations: 
Data comes in (xml, csv, dataset, netCDF ...), it gets transformed into triples through an ETL process according to the organisation's KG, and it is then ready to be queried with SPARQL. If a data consumer is lucky, he will get a GUI. If not, he will get an ugly SPARQL endpoint.
I can see the advantages of semantic web technologies, but -in your experience- is this approach also somewhat "boiling the ocean"?

**Comment by dwinston** [comment]
@xeniacs I like your observation. I have a related question, perhaps a rephrasing of yours:

What is Figure 1.7? (Or perhaps, what should have been Figure 4.1?)

That is, what is the Figure of a diagram akin in construction -- iconography and layout -- to Figures 1.1 through 1.6, that illustrates the vision of the book's approach that fills in the Data-Meaning gap of Figure 1.6? No such Figure is given in any subsequent chapter.

**Comment by msesboue** [comment]
Discussed in session 2 around 30 minutes
