### ISSUE TITLE
Could you describe how data management changes with knowledge graphs? + Expectations

### ISSUE THREAD

**Issue by MelMcCrea** [KGConf/BookClub-Designing-BuildingEnterpriseKG#8]
You open Ch1 saying that Data Management needs to change via a connection between data & knowledge. Following your line of argument, while there are many options for data management, only KG take semantics more seriously. But, how disruptive could this idea be for enterprises operating with RDBMS? what are some good pointers to keep in mind for this transformation?  
 

> Hi, :) My name is Mel and I'm a beginner in KG and when I say a beginner, I mean, more beginner than some beginner folks here. I've been working as a taxonomist for 5 years now. So, that's how I ended up here. 

Goals: 
- Gain more awareness of the building aspects of KG: I'd like to get a better understanding on mapping models to RDBMS 
- Practice some vicarious learning with the experiences of other people here 
- Identify some areas for further development

**Comment by msesboue** [comment]
Discussed in session 2 around 43 minutes
